defaults: &defaults
  working_directory: /home/circleci/project
  machine: true
  
version: 2
jobs:
  lint:
    docker:
      - image: alpine/helm
    steps:
      - checkout
      - run:
          name: Run helm lint for all chart directories
          command: |
            for c in $(find ./mercari -type d -maxdepth 1 -mindepth 1)
            do
              helm lint ${c}
            done
  sync:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: sync
          command: |
            script/ci/chart-sync mercari chartmuseum.dev.citadelapps.com/api/charts

workflows:
  version: 2
  lint:
    jobs:
      - lint
  sync:
    jobs:
      - sync
        filters:
          branches:
            only: master
