apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "pull-request-replication-controller.name" . }}
  labels:
    app: {{ template "pull-request-replication-controller.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "pull-request-replication-controller.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Chart.Name }}-github-token
                key: github_token
          - name: LOG_LEVEL
            value: {{ .Values.logLevel }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
